name: mz-giscup-26
channels:
  - conda-forge
dependencies:
  - python=3.11
  - shapely>=2.0
  - geopandas>=0.14
  - pyogrio>=0.7
  - numpy>=2.0
  - scipy>=1.11
  - pytest>=8
  - pip
  - pip:
      - -e .
